version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - HOTMART_WEBHOOK_SECRET=${HOTMART_WEBHOOK_SECRET}
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost/api

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend